### ISSUE TITLE
INI file missing

### ISSUE THREAD

**Issue by F4310** [fforchino/vector-go-sdk#4]
Please, can you help about it?

When i execute go run teste.go -serial myserial

2023/08/29 15:39:08 INI file missing
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9846d8]

goroutine 5 [running]:
github.com/fforchino/vector-go-sdk/pkg/vector.(*Vector).BehaviorControl(0x0?, {0xc25b30?, 0x400019a000?}, 0x0?, 0x0?)
        /root/go/pkg/mod/github.com/fforchino/vector-go-sdk@v0.0.0-20230501190038-5c1be0b59b5a/pkg/vector/behaviorcontrol.go:13 +0x28
main.main.func1()
        /root/wire-pod/teste.go:20 +0x38
created by main.main
        /root/wire-pod/teste.go:19 +0x16c
exit status 2

**Comment by TheGithubJoshua** [comment]
you need to make a .ini as stated in README.md

**Comment by TheGithubJoshua** [comment]
Actually, I tried it out and made the .ini file but I get the error.

**Comment by TheGithubJoshua** [comment]
@F4310 It works for me by ssh-ing into your wire-pod server, and running it there because in your home folder on wire-pod there is a .anki_vector folder with all the certs.

**Comment by F4310** [comment]
> @F4310 It works for me by ssh-ing into your wire-pod server, and running it there because in your home folder on wire-pod there is a .anki_vector folder with all the certs.

@TheGithubJoshua 
Could you explain the process in detail? I couldn't understand

**Comment by TheGithubJoshua** [comment]
@F4310 sorry for the late response .
SSH into your wire pod and build your go projects there.
